### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by GrantPerkins** [l5shi/Human-Detection-In-Depth-Image#1]
You do not have a license in your project, you should add one. 

The real reason why I'm creating this issue is to thank you. I'm a high school student and I've spent the last few months working on a somewhat related algorithm, and I've been desperately searching for another algorithm with which I can compare. All other algorithms that I've seen require a live Kinect to be connected and running, and do not provide any code. Thanks so much for doing this.

- Grant Perkins

**Comment by l5shi** [comment]
Thanks for your comment. I am too lazy to add one 😅
